/**:
  ros__parameters:
    kalman:
      process_noise:
        theta: 0.05
        x: 0.05
        y: 0.05
      sensor_noise: 0.1
    clusters:
      visualize: false
      threshold: 0.1 # m
    circles:
      visualize: false
      classification:
        mean_min: 0.0 # deg
        mean_max: 360.0  # deg
        std_dev_max: 1000.0 # deg
      radius_min: 0.01 # m
      radius_max: 0.1 # m
    mahalanobis:
      threshold: 0.25 # m